In [1]:
print("Trend Analysis Notebook")

Trend Analysis Notebook

# Import Library

In [2]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

In [3]:
DATA_PATH = "../data/processed/clean_children_data.csv"
df = pd.read_csv(DATA_PATH)
df

,date,cbp_daily_intake,cbp_custody,cbp_transfers_to_hhs,hhs_care,hhs_discharges,total_system_load,net_daily_intake,care_load_growth_rate,backlog_indicator,discharge_offset_ratio
0,2023-01-12,33.0,53.0,34.0,6566.0,436.0,6619.0,-402.0,NaN,False,12.823529
1,2023-01-22,32.0,49.0,39.0,7122.0,227.0,7171.0,-188.0,8.339628,False,5.820513
2,2023-01-23,32.0,50.0,39.0,7280.0,181.0,7330.0,-142.0,2.217264,False,4.641026
3,2023-01-24,47.0,42.0,47.0,7433.0,175.0,7475.0,-128.0,1.978172,False,3.723404
4,2023-01-25,20.0,22.0,41.0,7538.0,180.0,7560.0,-139.0,1.137124,False,4.390244
...,...,...,...,...,...,...,...,...,...,...,...
715,2025-12-15,11.0,42.0,9.0,2470.0,7.0,2512.0,2.0,0.600721,True,0.777778
716,2025-12-16,8.0,54.0,15.0,2468.0,9.0,2522.0,6.0,0.398089,True,0.600000
717,2025-12-17,7.0,31.0,11.0,2481.0,10.0,2512.0,1.0,-0.396511,True,0.909091
718,2025-12-18,11.0,50.0,6.0,2472.0,16.0,2522.0,-10.0,0.398089,False,2.666667
719,2025-12-21,6.0,18.0,11.0,2484.0,14.0,2502.0,-3.0,-0.793021,False,1.272727

# Daily Trend – Total System Load

In [4]:
fig = px.line(
    df,
    x="date",
    y="total_system_load",
    title="Daily Total System Load",
    labels={"date": "Date", "total_system_load": "Children Under Care"},
)

fig.update_traces(line=dict(width=2))
fig.update_layout(hovermode="x unified", template="plotly_white")
fig.show()

# Create Rolling Averages (Pressure Smoothing)

* Daily data noisy hota hai.
* Rolling average = true system pressure.

In [5]:
df["total_load_7d_avg"] = df["total_system_load"].rolling(7).mean()
df["total_load_14d_avg"] = df["total_system_load"].rolling(14).mean()

df["net_intake_7d_avg"] = df["net_daily_intake"].rolling(7).mean()
df["net_intake_14d_avg"] = df["net_daily_intake"].rolling(14).mean()

In [6]:
df

,date,cbp_daily_intake,cbp_custody,cbp_transfers_to_hhs,hhs_care,hhs_discharges,total_system_load,net_daily_intake,care_load_growth_rate,backlog_indicator,discharge_offset_ratio,total_load_7d_avg,total_load_14d_avg,net_intake_7d_avg,net_intake_14d_avg
0,2023-01-12,33.0,53.0,34.0,6566.0,436.0,6619.0,-402.0,NaN,False,12.823529,NaN,NaN,NaN,NaN
1,2023-01-22,32.0,49.0,39.0,7122.0,227.0,7171.0,-188.0,8.339628,False,5.820513,NaN,NaN,NaN,NaN
2,2023-01-23,32.0,50.0,39.0,7280.0,181.0,7330.0,-142.0,2.217264,False,4.641026,NaN,NaN,NaN,NaN
3,2023-01-24,47.0,42.0,47.0,7433.0,175.0,7475.0,-128.0,1.978172,False,3.723404,NaN,NaN,NaN,NaN
4,2023-01-25,20.0,22.0,41.0,7538.0,180.0,7560.0,-139.0,1.137124,False,4.390244,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
715,2025-12-15,11.0,42.0,9.0,2470.0,7.0,2512.0,2.0,0.600721,True,0.777778,2482.714286,2459.428571,-0.285714,0.000000
716,2025-12-16,8.0,54.0,15.0,2468.0,9.0,2522.0,6.0,0.398089,True,0.600000,2492.571429,2466.571429,0.428571,0.214286
717,2025-12-17,7.0,31.0,11.0,2481.0,10.0,2512.0,1.0,-0.396511,True,0.909091,2499.000000,2473.642857,-0.142857,0.214286
718,2025-12-18,11.0,50.0,6.0,2472.0,16.0,2522.0,-10.0,0.398089,False,2.666667,2506.000000,2480.000000,-1.428571,-1.214286
719,2025-12-21,6.0,18.0,11.0,2484.0,14.0,2502.0,-3.0,-0.793021,False,1.272727,2507.285714,2484.714286,-1.285714,-1.071429

# System Load Trend

In [7]:
fig = go.Figure()

fig.add_trace(
    go.Scatter(
        x=df["date"],
        y=df["total_system_load"],
        mode="lines",
        name="Daily Total System Load",
        line=dict(color="lightgray"),
    )
)

fig.add_trace(
    go.Scatter(
        x=df["date"],
        y=df["total_load_7d_avg"],
        mode="lines",
        name="7-Day Rolling Avg",
        line=dict(color="blue", width=3),
    )
)

fig.add_trace(
    go.Scatter(
        x=df["date"],
        y=df["total_load_14d_avg"],
        mode="lines",
        name="14-Day Rolling Avg",
        line=dict(color="red", width=3),
    )
)

fig.update_layout(
    title="Total System Load with Rolling Averages",
    xaxis_title="Date",
    yaxis_title="Number of Children",
    template="plotly_white",
)

fig.show()

# Net Intake Pressure Trend

In [8]:
fig = go.Figure()

fig.add_trace(
    go.Scatter(
        x=df["date"],
        y=df["net_daily_intake"],
        mode="lines",
        name="Daily Net Intake",
        line=dict(color="lightgray"),
    )
)

fig.add_trace(
    go.Scatter(
        x=df["date"],
        y=df["net_intake_7d_avg"],
        mode="lines",
        name="7-Day Avg Net Intake",
        line=dict(color="green", width=3),
    )
)

fig.add_trace(
    go.Scatter(
        x=df["date"],
        y=df["net_intake_14d_avg"],
        mode="lines",
        name="14-Day Avg Net Intake",
        line=dict(color="orange", width=3),
    )
)

fig.add_hline(y=0, line_dash="dash", line_color="black")

fig.update_layout(
    title="Net Intake Pressure Over Time",
    xaxis_title="Date",
    yaxis_title="Net Intake (Transfers − Discharges)",
    template="plotly_white",
)

fig.show()

# Care Load Volatility (Stability Indicator)

In [9]:
df["load_volatility_7d"] = df["total_system_load"].rolling(7).std()

In [10]:
df

,date,cbp_daily_intake,cbp_custody,cbp_transfers_to_hhs,hhs_care,hhs_discharges,total_system_load,net_daily_intake,care_load_growth_rate,backlog_indicator,discharge_offset_ratio,total_load_7d_avg,total_load_14d_avg,net_intake_7d_avg,net_intake_14d_avg,load_volatility_7d
0,2023-01-12,33.0,53.0,34.0,6566.0,436.0,6619.0,-402.0,NaN,False,12.823529,NaN,NaN,NaN,NaN,NaN
1,2023-01-22,32.0,49.0,39.0,7122.0,227.0,7171.0,-188.0,8.339628,False,5.820513,NaN,NaN,NaN,NaN,NaN
2,2023-01-23,32.0,50.0,39.0,7280.0,181.0,7330.0,-142.0,2.217264,False,4.641026,NaN,NaN,NaN,NaN,NaN
3,2023-01-24,47.0,42.0,47.0,7433.0,175.0,7475.0,-128.0,1.978172,False,3.723404,NaN,NaN,NaN,NaN,NaN
4,2023-01-25,20.0,22.0,41.0,7538.0,180.0,7560.0,-139.0,1.137124,False,4.390244,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
715,2025-12-15,11.0,42.0,9.0,2470.0,7.0,2512.0,2.0,0.600721,True,0.777778,2482.714286,2459.428571,-0.285714,0.000000,19.972600
716,2025-12-16,8.0,54.0,15.0,2468.0,9.0,2522.0,6.0,0.398089,True,0.600000,2492.571429,2466.571429,0.428571,0.214286,19.890175
717,2025-12-17,7.0,31.0,11.0,2481.0,10.0,2512.0,1.0,-0.396511,True,0.909091,2499.000000,2473.642857,-0.142857,0.214286,17.358955
718,2025-12-18,11.0,50.0,6.0,2472.0,16.0,2522.0,-10.0,0.398089,False,2.666667,2506.000000,2480.000000,-1.428571,-1.214286,14.821156
719,2025-12-21,6.0,18.0,11.0,2484.0,14.0,2502.0,-3.0,-0.793021,False,1.272727,2507.285714,2484.714286,-1.285714,-1.071429,13.864995

In [11]:
fig = px.line(
    df,
    x="date",
    y="load_volatility_7d",
    title="7-Day Care Load Volatility",
    labels={"load_volatility_7d": "Standard Deviation"},
    template="plotly_white",
)

fig.show()

# Stress Window Detection

* Logic:

1. Net intake positive
2. 7-day avg net intake positive
3. Sustained pressure

In [12]:
df["stress_window"] = (df["net_intake_7d_avg"] > 0) & (
    df["total_load_7d_avg"] > df["total_system_load"].median()
)

In [13]:
df

,date,cbp_daily_intake,cbp_custody,cbp_transfers_to_hhs,hhs_care,hhs_discharges,total_system_load,net_daily_intake,care_load_growth_rate,backlog_indicator,discharge_offset_ratio,total_load_7d_avg,total_load_14d_avg,net_intake_7d_avg,net_intake_14d_avg,load_volatility_7d,stress_window
0,2023-01-12,33.0,53.0,34.0,6566.0,436.0,6619.0,-402.0,NaN,False,12.823529,NaN,NaN,NaN,NaN,NaN,False
1,2023-01-22,32.0,49.0,39.0,7122.0,227.0,7171.0,-188.0,8.339628,False,5.820513,NaN,NaN,NaN,NaN,NaN,False
2,2023-01-23,32.0,50.0,39.0,7280.0,181.0,7330.0,-142.0,2.217264,False,4.641026,NaN,NaN,NaN,NaN,NaN,False
3,2023-01-24,47.0,42.0,47.0,7433.0,175.0,7475.0,-128.0,1.978172,False,3.723404,NaN,NaN,NaN,NaN,NaN,False
4,2023-01-25,20.0,22.0,41.0,7538.0,180.0,7560.0,-139.0,1.137124,False,4.390244,NaN,NaN,NaN,NaN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
715,2025-12-15,11.0,42.0,9.0,2470.0,7.0,2512.0,2.0,0.600721,True,0.777778,2482.714286,2459.428571,-0.285714,0.000000,19.972600,False
716,2025-12-16,8.0,54.0,15.0,2468.0,9.0,2522.0,6.0,0.398089,True,0.600000,2492.571429,2466.571429,0.428571,0.214286,19.890175,False
717,2025-12-17,7.0,31.0,11.0,2481.0,10.0,2512.0,1.0,-0.396511,True,0.909091,2499.000000,2473.642857,-0.142857,0.214286,17.358955,False
718,2025-12-18,11.0,50.0,6.0,2472.0,16.0,2522.0,-10.0,0.398089,False,2.666667,2506.000000,2480.000000,-1.428571,-1.214286,14.821156,False
719,2025-12-21,6.0,18.0,11.0,2484.0,14.0,2502.0,-3.0,-0.793021,False,1.272727,2507.285714,2484.714286,-1.285714,-1.071429,13.864995,False

# Visualize Stress Periods

In [14]:
fig = go.Figure()

fig.add_trace(
    go.Scatter(
        x=df["date"],
        y=df["total_system_load"],
        mode="lines",
        name="Total System Load",
        line=dict(color="lightblue"),
    )
)

fig.add_trace(
    go.Scatter(
        x=df[df["stress_window"]]["date"],
        y=df[df["stress_window"]]["total_system_load"],
        mode="markers",
        name="Stress Periods",
        marker=dict(color="red", size=6),
    )
)

fig.update_layout(
    title="Detected Capacity Stress Windows",
    xaxis_title="Date",
    yaxis_title="Total System Load",
    template="plotly_white",
)

fig.show()

# Quantify Stress Impact

In [15]:
stress_summary = {
    "total_days": len(df),
    "stress_days": df["stress_window"].sum(),
    "stress_percentage": (df["stress_window"].sum() / len(df)) * 100,
}

pd.DataFrame.from_dict(stress_summary, orient="index", columns=["value"])

                        value
total_days         720.000000
stress_days         82.000000
stress_percentage   11.388889

### Trend & Stress Analysis Insights

- Rolling averages reveal prolonged periods of elevated system load.
- Sustained positive net intake signals backlog accumulation risk.
- Detected stress windows indicate periods of heightened capacity strain.
- These insights can inform staffing, shelter expansion, and policy timing.

| Project Requirement (Given)               | Notebook mein kya kiya        |
| ----------------------------------------- | ----------------------------- |
| **Total care system load**                | `total_system_load`           |
| **Balance between inflow & outflow**      | `net_daily_intake`            |
| **Capacity stress & relief periods**      | Rolling avg + `stress_window` |
| **Sustainability over time**              | Growth rate + volatility      |
| **Daily / weekly / monthly trends**       | Rolling averages (7, 14 days) |
| **Backlog indicator**                     | `backlog_indicator`           |
| **Rolling averages (7,14)**               | Exactly implemented           |
| **Variability analysis**                  | `load_volatility_7d`          |
| **Detection of prolonged strain windows** | `stress_window` logic         |
| **KPIs**                                  | KPI summary table             |